name: Test ansibug
on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

  release:
    types:
    - published

jobs:
  sanity:
    name: run sanity checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        cache: pip
        cache-dependency-path: |
          pyproject.toml

    - name: Run sanity tests
      shell: bash
      run: |
        set -ex

        python -Im pip install tox
        python -Im tox run -f sanity

  build:
    name: build sdist and wheel
    needs:
    - sanity

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build sdist and wheel
      run: |
        set -ex

        python -m pip install build
        python -m build

    - uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: ./dist/*

  test:
    name: test
    needs:
      - build

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        ansible-version:
        - "2.14"
        - "2.15"
        - "2.16"
        - devel
        python-version:
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"

        exclude:
        # Exclude Python/Ansible versions that aren't compatible.
        - ansible-version: "2.14"
          python-version: "3.12"
        - ansible-version: "2.15"
          python-version: "3.12"
        - ansible-version: "2.16"
          python-version: "3.9"
        - ansible-version: devel
          python-version: "3.9"
        # Limit macOS tests to the bare essentials (2.16 only)
        - os: macos-latest
          ansible-version: "2.14"
        - os: macos-latest
          ansible-version: "2.15"
        - os: macos-latest
          ansible-version: devel

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            pyproject.toml

      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: ./dist

      - name: Calculate env vars
        shell: bash
        run: |
          set -ex
          OS=$( echo '${{ matrix.os }}' | tr '-' ' ' | awk '{print $1}' )
          echo "OS=${OS}" >> $GITHUB_ENV

          TOX_PYTHON=py$( echo '${{ matrix.python-version }}' | tr -d . )
          echo "TOX_PYTHON=${TOX_PYTHON}" >> $GITHUB_ENV

      - name: Test
        shell: bash
        run: |
          set -ex

          python -Im pip install tox
          python -Im tox run \
              -f ${{ env.TOX_PYTHON }} ansible_${{ matrix.ansible-version }} \
              --installpkg dist/*.whl
        env:
          PYTEST_ADDOPTS: --color=yes --junitxml junit/test-results.xml

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Unit Test Results (${{ matrix.os }} ${{ matrix.python-version }} ansible_${{ matrix.ansible-version }})
          path: ./junit/test-results.xml

      - name: Upload Coverage Results
        if: always() && !startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v3
        with:
          name: Coverage Results (${{ matrix.os }} ${{ matrix.python-version }} ansible_${{ matrix.ansible-version }})
          path: ./coverage.xml

      - name: Upload Coverage to codecov
        if: always()
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: ${{ env.OS }},py${{ matrix.python-version }},ansible_${{ matrix.ansible-version }}

  publish:
    name: publish
    needs:
    - test
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: ./dist

    - name: Publish
      if: startsWith(github.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@release/v1



      
